version: '3.8'
services:
  python27:
    build:
      context: .
      args:
        PYTHON_VERSION: "2.7"
    image: python27-pytest

  python36:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.6"
    image: python36-pytest

  python310:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.10"
    image: python310-pytest
