name: Black Formatting

on:
  workflow_call:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: psf/black@stable
      with:
          options: "--check --verbose"
          src: "./src"
          version: "~= 22.0"
