name: Black Formatting

on:
  workflow_call:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: psf/black@stable
      with:
          options: "--check --verbose"
          src: "."
          version: "~= 22.0"
