name: Main

on:
  workflow_dispatch:
  pull_request:
      branches:
        - master

jobs:
  detect-file-changes:
    runs-on: ubuntu-latest
    outputs:
      docker_changes: ${{ steps.changes.outputs.docker_changes }}
      oom_investigate: ${{ steps.changes.outputs.oom_investigate }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
            docker_changes:
              - "Dockerfile"
              - "docker-compose.yml"
            oom_investigate:
              - ".github/workflows/*.yml"
              - "tests/**/*"
              - "oom_investigate.py"

  build-pytest-images:
      needs:
          - detect-file-changes
      uses: ./.github/workflows/build-pytest-images.yml
      if: needs.detect-file-changes.outputs.docker_changes == 'true'
      secrets: inherit

  black:
      needs:
          - detect-file-changes
      uses: ./.github/workflows/black.yml
      if: needs.detect-file-changes.outputs.oom_investigate == 'true'

  isort:
      needs:
          - detect-file-changes
      uses: ./.github/workflows/isort.yml
      if: needs.detect-file-changes.outputs.oom_investigate == 'true'

  # pytest:
  #     needs:
  #         - detect-file-changes
  #     uses: ./.github/workflows/pytest.yml
  #     if: needs.detect-file-changes.outputs.oom_investigate == 'true'
