name: Run Unit Tests on Multiple Python Versions

on:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3,6", "3.10"]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests/
